# Generated by Django 4.1.2 on 2022-11-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_username_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contentn',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='imge',
            new_name='image',
        ),
    ]
