# Generated by Django 4.1.3 on 2022-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_portfolio_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='customers/images/'),
        ),
    ]
