# Generated by Django 4.1.3 on 2022-11-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_portfolio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Customer',
            new_name='customer',
        ),
    ]
