# Generated by Django 4.1.3 on 2022-11-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_rename_customer_portfolio_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='format',
            new_name='case',
        ),
    ]
