# Generated by Django 4.1.3 on 2022-11-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
