# Generated by Django 4.1.3 on 2022-11-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
