# Generated by Django 4.1.3 on 2022-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_remove_order_image_remove_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolio_image')),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='order_image')),
            ],
        ),
    ]
