# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
