# Generated by Django 4.1.3 on 2022-12-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0024_alter_portfolio_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
