# Generated by Django 4.1.3 on 2022-12-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_alter_portfolio_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='created_by',
            new_name='creator',
        ),
    ]
