# Generated by Django 4.1.3 on 2022-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_remove_order_title_remove_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='case',
            field=models.CharField(choices=[('پوستر', 'پوستر'), ('بنر', 'بنر'), ('بیزینس کارت', 'بیزینس کارت'), ('لوگو', 'لوگو')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='case',
            field=models.CharField(choices=[('پوستر', 'پوستر'), ('بنر', 'بنر'), ('بیزینس کارت', 'بیزینس کارت'), ('لوگو', 'لوگو')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
