# Generated by Django 4.1.3 on 2023-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_alter_order_case_alter_portfolio_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='case',
            field=models.CharField(choices=[('پوستر', 'پوستر'), ('بنر', 'بنر'), ('بیزینس کارت', 'بیزینس کارت'), ('لوگو', 'لوگو'), ('وکتور', 'وکتور')], max_length=50),
        ),
    ]
